project_conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns

from project.views import logout, Index, UserList, UserDetail, CurrentUserDetail

admin.autodiscover()

urlpatterns = patterns('',
    (r'^api/', include(patterns('',
        url(r'^user$', CurrentUserDetail.as_view(), name='user'),
        url(r'^users$', UserList.as_view(), name='user-list'),
        url(r'^users/(?P<pk>\d+)$', UserDetail.as_view(), name='user-detail'),
    ))),
)

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

# Default login/logout views
urlpatterns += patterns('',
    url(r'^$', Index.as_view(), name='index'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),
)

project/models.py
# -*- coding: utf-8 -*-
__author__ = 'gzbender'

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    GENDER_CHOICES = (
        ('male', u'Male'),
        ('female', u'Female'),
    )
    gender = models.CharField(u'Gender', choices=GENDER_CHOICES, max_length=6, blank=True)
    age = models.SmallIntegerField(u'Age', db_index=True, default=0)

project/views.py
# -*- coding: utf-8 -*-
__author__ = 'gzbender'

from rest_framework import generics
from rest_framework.permissions import IsAdminUser
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth.views import logout as auth_logout

from project.serializers import UserSerializer
from project.models import User


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return redirect('/')


class Index(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class UserList(generics.ListAPIView):
    model = User
    serializer_class = UserSerializer
    permission_classes = (IsAdminUser,)
    filter_fields = ('age',)


class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    model = User
    serializer_class = UserSerializer
    permission_classes = (IsAdminUser,)


class CurrentUserDetail(generics.RetrieveUpdateAPIView):
    model = User
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user

    def patch(self, request, *args, **kwargs):
        response = super(CurrentUserDetail, self).patch(request, *args, **kwargs)
        if response.status_code == 200:
            response.status_code = 202
        return response

conf/vagrant/salt/roots/salt/nginx/templates/config.jinja
{% set nginx = pillar.get('nginx', {}) -%}
{% set user = nginx.get('user', 'www-data') -%}
{% set group = nginx.get('group', 'www-data') -%}
user   {{ user }} {{ group }};
worker_processes  {{ nginx.get('worker_processes', 1) }};

error_log /var/log/nginx/error.fifo warn;
pid {{ nginx.get('pid', '/var/run/nginx.pid') }};
daemon {{ nginx.get('daemon', 'off') }};

events {
    worker_connections {{ nginx.get('events', {}).get('worker_connections', 1024) }};
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format main '$scheme://$host:$server_port$uri$is_args$args $remote_addr:$remote_user "$request" $request_time $request_length:$bytes_sent $status "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.fifo main;
    sendfile {{ nginx.get('sendfile', 'on') }};
    #tcp_nopush on;
    keepalive_timeout {{ nginx.get('keepalive_timeout', 65) }};
    server_names_hash_bucket_size {{ nginx.get('server_names_hash_bucket_size', 128) }};
    server_names_hash_max_size {{ nginx.get('server_names_hash_max_size', 1024) }};
    types_hash_max_size {{ nginx.get('types_hash_max_size', 8192) }};

    gzip {{ nginx.get('gzip', 'on') }};
    gzip_vary {{ nginx.get('gzip_vary', 'on') }};
    gzip_proxied {{ nginx.get('gzip_proxied', 'any') }};
    gzip_comp_level {{ nginx.get('gzip_comp_level', 6) }};
    gzip_buffers {{ nginx.get('gzip_buffers', '16 8k') }};
    gzip_http_version {{ nginx.get('gzip_http_version', '1.1') }};
    gzip_types {{ nginx.get('gzip_types', ['text/plain', 'text/css', 'application/json', 'application/x-javascript', 'text/xml', 'application/xml', 'application/xml+rss', 'text/javascript'])|join(' ') }};

    # turn on nginx_status on localhost
    server {
        listen 127.0.0.1:80;
        server_name 127.0.0.1;
        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
{% if pillar['nginx'] is defined -%}
{% if pillar['nginx']['redirect_numeric_ip']|default(False) %}
    server {
        server_name {% for ip in salt['network.interfaces']()['eth0']['inet'] %}{{ ip['address'] }}:80{% if not loop.last %} {% endif %}{% endfor %};
        return 302 {{ pillar['nginx']['redirect_numeric_ip'] }};
        access_log off;
    }
{% endif %}
{% endif %}

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*.conf;
}

conf/vagrant/salt/roots/salt/nginx/templates/upstart-logger.jinja
# {{ pillar.get('message_do_not_modify', '') }}
# startup script for Nginx loggers

start on starting nginx
stop on runlevel [!2345]

respawn

pre-start script
    if [ ! -r /var/log/nginx/{{ type }}.fifo ]; then
        mkfifo /var/log/nginx/{{ type }}.fifo
        chown root.root /var/log/nginx/{{ type }}.fifo
        chmod 660 /var/log/nginx/{{ type }}.fifo
    fi
end script

emits nginx-logger-{{ type }}

exec logger -f /var/log/nginx/{{ type }}.fifo -t nginx -p {% if type == 'error' %}warn{% else %}debug{% endif %}

conf/vagrant/salt/roots/salt/nginx/templates/upstart.jinja
# startup script for Nginx

respawn

start on filesystem or runlevel [2345]
stop on runlevel [!2345]

exec /usr/sbin/nginx -c /etc/nginx/nginx.conf

project/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div>
            Вы&nbsp;вошли&nbsp;как<br/>
            <span style="font-size: 24px;">{{ user.first_name }}&nbsp;{{ user.last_name }}</span><br/>
            {% if user.age > 0 %}возраст:&nbsp;{{ user.age }}<br/>{% endif %}
            {% if user.gender %}пол:&nbsp;{{ user.get_gender_display }}<br/>{% endif %}
            <a href="{% url 'logout' %}">Выйти</a>
        </div>
    {% else %}
        <a href="{% url 'social:begin' "vk-oauth2" %}" class="vk sn-logo">Authorize by vk</a><br />
        <a href="{% url 'social:begin' "facebook" %}" class="fb sn-logo">Authorize by facebook</a>
    {% endif %}
{% endblock content %}

project/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}{% endblock content %}
</body>
</html>